### ISSUE TITLE
Theme Review Checklist

### ISSUE THREAD

**Issue by david-binda** [david-binda/test#1]
- [ ] You've reviewed your code for [common blockers](https://vip.wordpress.com/documentation/code-review-what-we-look-for/).
- [ ] Your theme/plugins are either licensed under the GNU Public License v2 (GPL2), a compatible license, or are completely custom code that you've written in-house—split or proprietary licenses are not allowed. The reasoning for this is that you, and we, need to have the legal rights to modify the code if something is broken, insecure, needs optimization, etc.
- [ ] Your code has been QA'ed in an up-to-date [VIP GO Quickstart environment](https://github.com/Automattic/vip-go-quickstart).
- [ ] Your code has been run through the [VIP Scanner](http://wordpress.org/plugins/vip-scanner/), all blocker-level issues are addressed, and non-blocking errors detailed in your submission materials.
- [ ] All data is properly [validated, sanitized, and escaped](https://vip.wordpress.com/documentation/validating-sanitizing-escaping/). The first two apply to whenever you're handing user-submitted data (e.g. post meta boxes, frontend forms, etc.) and the latter applies to whenever you're printing data from the database.
- [ ] Scripts and styles are enqueued, and are done so on the [proper hook](http://wpdevel.wordpress.com/2011/12/12/use-wp_enqueue_scripts-not-wp_print_styles-to-enqueue-scripts-and-styles-for-the-frontend/).
- [ ] The theme does not use [query_posts()](http://developer.wordpress.com/2012/05/14/querying-posts-without-query_posts/).
- [ ] All custom functions, classes, options, constants, custom post types, custom taxonomies, script handlers, and style handlers [are prefixed](http://nacin.com/2010/05/11/in-wordpress-prefix-everything/).
- [ ] The [vip_powered_wpcom()](https://vip.wordpress.com/documentation/powered-by-wordpress-com/) function is called in the theme's footer.php.
- [ ] The theme follows [WordPress Coding Standards](http://codex.wordpress.org/WordPress_Coding_Standards).
